/// Cross-check our from-scratch BIP39 against the official `bip39` crate's output.
/// These expected values were generated by bip39 v2.2.2.

use kerrigan_wallet::bip39::{entropy_to_mnemonic, mnemonic_to_seed, validate_mnemonic};
use kerrigan_wallet::encoding::{hex_encode, hex_decode};

struct Vector {
    entropy: &'static str,
    passphrase: &'static str,
    expected_mnemonic: &'static str,
    expected_seed: &'static str,
}

const VECTORS: &[Vector] = &[
    Vector {
        entropy: "00000000000000000000000000000000",
        passphrase: "TREZOR",
        expected_mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
        expected_seed: "c55257c360c07c72029aebc1b53c05ed0362ada38ead3e3e9efa3708e53495531f09a6987599d18264c1e1c92f2cf141630c7a3c4ab7c81b2f001698e7463b04",
    },
    Vector {
        entropy: "7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f",
        passphrase: "TREZOR",
        expected_mnemonic: "legal winner thank year wave sausage worth useful legal winner thank yellow",
        expected_seed: "2e8905819b8723fe2c1d161860e5ee1830318dbf49a83bd451cfb8440c28bd6fa457fe1296106559a3c80937a1c1069be3a3a5bd381ee6260e8d9739fce1f607",
    },
    Vector {
        entropy: "ffffffffffffffffffffffffffffffff",
        passphrase: "TREZOR",
        expected_mnemonic: "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo wrong",
        expected_seed: "ac27495480225222079d7be181583751e86f571027b0497b5b5d11218e0a8a13332572917f0f8e5a589620c6f15b11c61dee327651a14c34e18231052e48c069",
    },
    Vector {
        entropy: "0000000000000000000000000000000000000000000000000000000000000000",
        passphrase: "TREZOR",
        expected_mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art",
        expected_seed: "bda85446c68413707090a52022edd26a1c9462295029f2e60cd7c4f2bbd3097170af7a4d73245cafa9c3cca8d561a7c3de6f5d4a10be8ed2a5e608d68f92fcc8",
    },
    Vector {
        entropy: "68a79eead171a4d1c6b5dc1cbf0b7a4e8ef72e0b7b7b7c7d7e7f808182838485",
        passphrase: "",
        expected_mnemonic: "hamster diagram rival pepper bottom happy bracket romance bronze weapon teach other urge novel combine hunt ladder typical paper absurd blouse dove bamboo poem",
        expected_seed: "8b0e25e5e5e0785db89761fa75fa35ae22dd9a2d749ffa7189ea6a7d509923ac592356ffbcebd9a775a61601f3c84c78f64e02b7442c40b3eedfdeeff00324db",
    },
    Vector {
        entropy: "abcdef0123456789abcdef0123456789",
        passphrase: "",
        expected_mnemonic: "profit hunt scare educate filter shadow quality sadness abuse boss fly bar",
        expected_seed: "40c8804c7aa570cb454cb81a8612bd447f9cc234d2728f76f8196b6e37f244c881baceaa5c91d66d39447210fc8b4b594b62d24c84a27ecc428c847d35dda47c",
    },
];

#[test]
fn crosscheck_mnemonic_generation() {
    for (i, v) in VECTORS.iter().enumerate() {
        let entropy = hex_decode(v.entropy).unwrap();
        let mnemonic = entropy_to_mnemonic(&entropy).unwrap();
        assert_eq!(
            mnemonic, v.expected_mnemonic,
            "Vector {i}: mnemonic mismatch for entropy {}",
            v.entropy
        );
    }
}

#[test]
fn crosscheck_seed_derivation() {
    for (i, v) in VECTORS.iter().enumerate() {
        let seed = mnemonic_to_seed(v.expected_mnemonic, v.passphrase);
        assert_eq!(
            hex_encode(&seed), v.expected_seed,
            "Vector {i}: seed mismatch for mnemonic '{}'",
            v.expected_mnemonic
        );
    }
}

#[test]
fn crosscheck_validation() {
    for v in VECTORS {
        validate_mnemonic(v.expected_mnemonic)
            .unwrap_or_else(|e| panic!("Validation failed for '{}': {e}", v.expected_mnemonic));
    }
}

#[test]
fn crosscheck_full_pipeline() {
    for (i, v) in VECTORS.iter().enumerate() {
        let entropy = hex_decode(v.entropy).unwrap();

        // entropy → mnemonic
        let mnemonic = entropy_to_mnemonic(&entropy).unwrap();
        assert_eq!(mnemonic, v.expected_mnemonic, "Vector {i}: mnemonic");

        // mnemonic → validate
        validate_mnemonic(&mnemonic).unwrap();

        // mnemonic → seed
        let seed = mnemonic_to_seed(&mnemonic, v.passphrase);
        assert_eq!(hex_encode(&seed), v.expected_seed, "Vector {i}: seed");
    }
}
